# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f4091ad1cc7081a683b6748df8807aff8a0f02264c9d223c56900dd96354d93d99640f55e5e5f87523bc1acccb3c4bbfd972ac0c3dc82ca269fb4682a57cf16

test:
  secret_key_base: 406a1c20efe8e13d8ad7a4c1754f68561af98470908ce0f6fd8194ada923a94a6345746dbfe57d9d0c1c15058c94d1fae1cc492da347c7ab4da3cd6010fa9220

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
